package com.mycompany.controlsoftware;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ING. JUNIOR MORALES
 */
public class mantenimiento_devoluciones_ctd extends javax.swing.JInternalFrame {

    /**
     * Creates new form seleccionarfactura
     */
    BaseDeDatos bd = new BaseDeDatos();

    public mantenimiento_devoluciones_ctd() {
        super("Usuario: " + new BaseDeDatos().valor("select user from usuario where cod_user=" + ControlSoftware.us) + ", Sucursal: " + new BaseDeDatos().valor("select company from company where id_company=" + ControlSoftware.cia));

        UIManager.put("TableHeaderUI", "javax.swing.plaf.basic.BasicTableHeaderUI");
        initComponents();

        bd.LlenarTabla("select devolucion.id_devolucion as COD, devolucion.n_devolucion as NDEVOLUCION, factura.numerofactura AS NFACTURA, CASE factura.tipo WHEN '1' THEN 'ORIGINAL' WHEN '0' THEN 'CP' END as TIPOFACTURA, cliente.Nombre as CLIENTE, devolucion.subtotal as SUBTOTAL, devolucion.isv as ISV, devolucion.total as TOTAL, devolucion.fecha_devolucion as FECHA_DEVOLUCION, devolucion.fecha_sistema as FECHA_SISTEMA, usuario.user as USUARIO_DEVUELVE, devolucion.observacion as OBS, CASE devolucion.estado WHEN '0' THEN 'ANULADA' WHEN '1' THEN 'INGRESADA' END AS ESTADO FROM devoluciones devolucion inner join factura factura on devolucion.id_factura=factura.idfactura inner join clientes cliente on cliente.idcliente=factura.idcliente inner join usuario usuario on usuario.cod_user=devolucion.idusuario where devolucion.cia=" + ControlSoftware.cia + " AND FACTURA.CONDICIONPAGO=1 order by devolucion.fecha_devolucion desc", Productos);
        Productos.setDefaultRenderer(Object.class, new MiRendererNC());
//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh72.png")));
//        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add72.png")));
//        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel72.png")));
//        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer72.png")));
//        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar72.png")));
//        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back72.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pfecha = new javax.swing.JRadioButton();
        ninguno = new javax.swing.JRadioButton();
        todos = new javax.swing.JRadioButton();
        pnumero = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dnumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hnumero = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dfecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        hfecha = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        cliente = new javax.swing.JTextField();
        pcliente = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(195, 180, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "FILTROS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        pfecha.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(pfecha);
        pfecha.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pfecha.setForeground(new java.awt.Color(0, 0, 0));
        pfecha.setText("POR FECHA");

        ninguno.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(ninguno);
        ninguno.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ninguno.setForeground(new java.awt.Color(0, 0, 0));
        ninguno.setSelected(true);
        ninguno.setText("NINGUNO");

        todos.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(todos);
        todos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        todos.setForeground(new java.awt.Color(0, 0, 0));
        todos.setText("TODOS");

        pnumero.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(pnumero);
        pnumero.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pnumero.setForeground(new java.awt.Color(0, 0, 0));
        pnumero.setText("POR NUMERO");

        jPanel2.setBackground(new java.awt.Color(195, 180, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "POR NUMERO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DESDE");

        dnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dnumeroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dnumeroKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("HASTA");

        hnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hnumeroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hnumeroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(dnumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(hnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(195, 180, 225));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "POR FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DESDE");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("HASTA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(dfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(dfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(195, 180, 225));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "POR CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cliente)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pcliente.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(pcliente);
        pcliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pcliente.setForeground(new java.awt.Color(0, 0, 0));
        pcliente.setText("POR CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pcliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pfecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ninguno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addComponent(todos)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ninguno)
                            .addComponent(todos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pfecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pcliente)))
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(195, 180, 225));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back24.png"))); // NOI18N
        jButton5.setText("REGRESAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print24.png"))); // NOI18N
        jButton6.setText("IMPRIMIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete24.png"))); // NOI18N
        jButton4.setText("ELIMINAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel24.png"))); // NOI18N
        jButton3.setText("ANULAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevo24.png"))); // NOI18N
        jButton2.setText("NUEVA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh24.png"))); // NOI18N
        jButton1.setText("REFRESCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jScrollPane1.setAutoscrolls(true);

        Productos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Productos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Productos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        Productos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Productos.getTableHeader().setReorderingAllowed(false);
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
        });
        Productos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ProductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Productos);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MANTENIMIENTO DE DEVOLUCIONES CTD");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CONTROLSOFTWARE - COPYRIGHT 2023 - ING. JUNIOR MORALES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            Date date1;
            date1 = dfecha.getDate();
            Date date2;
            date2 = hfecha.getDate();
            if (ninguno.isSelected()) {
                bd.LlenarTabla("select devolucion.id_devolucion as COD, devolucion.n_devolucion as NDEVOLUCION, factura.numerofactura AS NFACTURA, CASE factura.tipo WHEN '1' THEN 'ORIGINAL' WHEN '0' THEN 'CP' END as TIPOFACTURA, cliente.Nombre as CLIENTE, devolucion.subtotal as SUBTOTAL, devolucion.isv as ISV, devolucion.total as TOTAL, devolucion.fecha_devolucion as FECHA_DEVOLUCION, devolucion.fecha_sistema as FECHA_SISTEMA, usuario.user as USUARIO_DEVUELVE, devolucion.observacion as OBS, CASE devolucion.estado WHEN '0' THEN 'ANULADA' WHEN '1' THEN 'INGRESADA' END AS ESTADO FROM devoluciones devolucion inner join factura factura on devolucion.id_factura=factura.idfactura inner join clientes cliente on cliente.idcliente=factura.idcliente inner join usuario usuario on usuario.cod_user=devolucion.idusuario where devolucion.cia=" + ControlSoftware.cia+" AND FACTURA.CONDICIONPAGO=1", Productos);
            } else if (pnumero.isSelected() && !dnumero.getText().isEmpty() && !hnumero.getText().isEmpty()) {
                bd.LlenarTabla("select devolucion.id_devolucion as COD, devolucion.n_devolucion as NDEVOLUCION, factura.numerofactura AS NFACTURA, CASE factura.tipo WHEN '1' THEN 'ORIGINAL' WHEN '0' THEN 'CP' END as TIPOFACTURA, cliente.Nombre as CLIENTE, devolucion.subtotal as SUBTOTAL, devolucion.isv as ISV, devolucion.total as TOTAL, devolucion.fecha_devolucion as FECHA_DEVOLUCION, devolucion.fecha_sistema as FECHA_SISTEMA, usuario.user as USUARIO_DEVUELVE, devolucion.observacion as OBS, CASE devolucion.estado WHEN '0' THEN 'ANULADA' WHEN '1' THEN 'INGRESADA' END AS ESTADO FROM devoluciones devolucion inner join factura factura on devolucion.id_factura=factura.idfactura inner join clientes cliente on cliente.idcliente=factura.idcliente inner join usuario usuario on usuario.cod_user=devolucion.idusuario where devolucion.cia=" + ControlSoftware.cia + " AND FACTURA.CONDICIONPAGO=1 and devolucion.n_devolucion between " + dnumero.getText() + " and " + hnumero.getText(), Productos);
            } else if (pfecha.isSelected() && !(date1 == null) && !(date2 == null)) {
                if (date2.compareTo(date1) == -1) {
                    JOptionPane.showMessageDialog(null, "La fecha final no puede ser mayor a la inicial.");
                } else {
                    bd.LlenarTabla("select devolucion.id_devolucion as COD, devolucion.n_devolucion as NDEVOLUCION, factura.numerofactura AS NFACTURA, CASE factura.tipo WHEN '1' THEN 'ORIGINAL' WHEN '0' THEN 'CP' END as TIPOFACTURA, cliente.Nombre as CLIENTE, devolucion.subtotal as SUBTOTAL, devolucion.isv as ISV, devolucion.total as TOTAL, devolucion.fecha_devolucion as FECHA_DEVOLUCION, devolucion.fecha_sistema as FECHA_SISTEMA, usuario.user as USUARIO_DEVUELVE, devolucion.observacion as OBS, CASE devolucion.estado WHEN '0' THEN 'ANULADA' WHEN '1' THEN 'INGRESADA' END AS ESTADO FROM devoluciones devolucion inner join factura factura on devolucion.id_factura=factura.idfactura inner join clientes cliente on cliente.idcliente=factura.idcliente inner join usuario usuario on usuario.cod_user=devolucion.idusuario where devolucion.cia=" + ControlSoftware.cia + " AND FACTURA.CONDICIONPAGO=1 and devolucion.fecha_sistema between '" + Date_Format.format(dfecha.getDate()) + "' and '" + Date_Format.format(hfecha.getDate()) + "'", Productos);
                }
            } else if (pcliente.isSelected() && !cliente.getText().isEmpty()) {
                bd.LlenarTabla("select devolucion.id_devolucion as COD, devolucion.n_devolucion as NDEVOLUCION, factura.numerofactura AS NFACTURA, CASE factura.tipo WHEN '1' THEN 'ORIGINAL' WHEN '0' THEN 'CP' END as TIPOFACTURA, cliente.Nombre as CLIENTE, devolucion.subtotal as SUBTOTAL, devolucion.isv as ISV, devolucion.total as TOTAL, devolucion.fecha_devolucion as FECHA_DEVOLUCION, devolucion.fecha_sistema as FECHA_SISTEMA, usuario.user as USUARIO_DEVUELVE, devolucion.observacion as OBS, CASE devolucion.estado WHEN '0' THEN 'ANULADA' WHEN '1' THEN 'INGRESADA' END AS ESTADO FROM devoluciones devolucion inner join factura factura on devolucion.id_factura=factura.idfactura inner join clientes cliente on cliente.idcliente=factura.idcliente inner join usuario usuario on usuario.cod_user=devolucion.idusuario where devolucion.cia=" + ControlSoftware.cia + " AND FACTURA.CONDICIONPAGO=1 and c.nombre like '%" + cliente.getText() + "%'", Productos);
            } else if (todos.isSelected() && !dnumero.getText().isEmpty() && !hnumero.getText().isEmpty() && !cliente.getText().isEmpty() && !dfecha.getDate().equals("") && !hfecha.getDate().equals("")) {
                if (date2.compareTo(date1) == -1) {
                    JOptionPane.showMessageDialog(null, "La fecha final no puede ser mayor a la inicial.");
                } else {
                    bd.LlenarTabla("select devolucion.id_devolucion as COD, devolucion.n_devolucion as NDEVOLUCION, factura.numerofactura AS NFACTURA, CASE factura.tipo WHEN '1' THEN 'ORIGINAL' WHEN '0' THEN 'CP' END as TIPOFACTURA, cliente.Nombre as CLIENTE, devolucion.subtotal as SUBTOTAL, devolucion.isv as ISV, devolucion.total as TOTAL, devolucion.fecha_devolucion as FECHA_DEVOLUCION, devolucion.fecha_sistema as FECHA_SISTEMA, usuario.user as USUARIO_DEVUELVE, devolucion.observacion as OBS, CASE devolucion.estado WHEN '0' THEN 'ANULADA' WHEN '1' THEN 'INGRESADA' END AS ESTADO FROM devoluciones devolucion inner join factura factura on devolucion.id_factura=factura.idfactura inner join clientes cliente on cliente.idcliente=factura.idcliente inner join usuario usuario on usuario.cod_user=devolucion.idusuario where devolucion.cia=" + ControlSoftware.cia + " AND FACTURA.CONDICIONPAGO=1 and c.nombre like '%" + cliente.getText() + "%'" + " and devolucion.fecha_sistema between '" + Date_Format.format(dfecha.getDate()) + "' and '" + Date_Format.format(hfecha.getDate()) + "'" + " and devolucion.n_devolucion between " + dnumero.getText() + " and " + hnumero.getText(), Productos);
                }

            } else {
                bd.LlenarTabla("select devolucion.id_devolucion as COD, devolucion.n_devolucion as NDEVOLUCION, factura.numerofactura AS NFACTURA, CASE factura.tipo WHEN '1' THEN 'ORIGINAL' WHEN '0' THEN 'CP' END as TIPOFACTURA, cliente.Nombre as CLIENTE, devolucion.subtotal as SUBTOTAL, devolucion.isv as ISV, devolucion.total as TOTAL, devolucion.fecha_devolucion as FECHA_DEVOLUCION, devolucion.fecha_sistema as FECHA_SISTEMA, usuario.user as USUARIO_DEVUELVE, devolucion.observacion as OBS, CASE devolucion.estado WHEN '0' THEN 'ANULADA' WHEN '1' THEN 'INGRESADA' END AS ESTADO FROM devoluciones devolucion inner join factura factura on devolucion.id_factura=factura.idfactura inner join clientes cliente on cliente.idcliente=factura.idcliente inner join usuario usuario on usuario.cod_user=devolucion.idusuario where FACTURA.CONDICIONPAGO=1 AND devolucion.cia=" + ControlSoftware.cia, Productos);

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosKeyReleased

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ProductosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String perm = "89";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permitido ingresar notas de crédito.");
            return;
        }
        ingresar_devolucion_ctd l = new ingresar_devolucion_ctd();
        Dimension internalFrameSize = l.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        l.setLocation((screenSize.width - internalFrameSize.width) / 2,
                (screenSize.height - internalFrameSize.height) / 2);
        DESKSOFTWARE.escritorio.add(l);
        l.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dnumeroKeyTyped
        int key = evt.getKeyChar();
        if (!(key == '0' || key == '1' || key == '2' || key == '3' || key == '4' || key == '5' || key == '6' || key == '7' || key == '8' || key == '9' || key == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_dnumeroKeyTyped

    private void dnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dnumeroKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_dnumeroKeyReleased

    private void hnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hnumeroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hnumeroKeyReleased

    private void hnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hnumeroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hnumeroKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        String perm = "90";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permitido anular notas de crédito.");
            return;
        }
        try {
            if (!Productos.getValueAt(Productos.getSelectedRow(), 12).toString().equals("INGRESADA")) {
                JOptionPane.showMessageDialog(null, "Esta devolución ya está anulada.");
            } else {

                int x = JOptionPane.showConfirmDialog(null, "Está seguro de anular esta factura?");
                if (x == 0) {

                    String id_devolucion = Productos.getValueAt(Productos.getSelectedRow(), 0).toString();

                    String motivo_anulacion = JOptionPane.showInputDialog(null, "Ingrese el motivo de anulación");
                    String user = bd.valor("select idusuario from devoluciones where id_devolucion=" + id_devolucion + " and cia=" + ControlSoftware.cia);
                    motivo_anulacion += ", anulado, usuario que realizó la nota de crédito: " + bd.valor("select user from usuario where cod_user=" + user);

                    String id_factura = bd.valor("select id_factura from devoluciones where id_devolucion=" + id_devolucion + " and cia=" + ControlSoftware.cia);
                    String tipof = bd.valor("select tipo from factura where idfactura=" + id_factura + " and cia=" + ControlSoftware.cia);
                    String tipon = "7";
                    if (tipof.equals("0")) {
                        tipon = "6";
                    }
                    String id_cliente = bd.valor("select idcliente from factura where idfactura=" + id_factura + " and cia=" + ControlSoftware.cia);
                    String montodev = bd.valor("select total from devoluciones where id_devolucion=" + id_devolucion + " and id_factura=" + id_factura + " and cia=" + ControlSoftware.cia);
                        String total_factura = bd.valor("select total from factura where idfactura=" + id_factura + " and cia=" + ControlSoftware.cia);
                    String saldo_factura = bd.valor("select saldo from factura where idfactura=" + id_factura + " and cia=" + ControlSoftware.cia);
//                
                      double total_factura1 = Double.parseDouble(bd.valor("select total from factura where idfactura=" + id_factura + " and cia=" + ControlSoftware.cia));
                    double saldo_factura1 = Double.parseDouble(bd.valor("select saldo from factura where idfactura=" + id_factura + " and cia=" + ControlSoftware.cia));

                   
                    String producto_a_rebajar[] = bd.Llenar("select id_producto from detalle_devolucion where id_devolucion=" + id_devolucion, "id_producto");
                    for (int i = 0; i < producto_a_rebajar.length; i++) {
                        int qty = Integer.parseInt(bd.valor("select cantidad from detalle_devolucion where id_devolucion=" + id_devolucion + " and id_producto=" + producto_a_rebajar[i] + " and cia=" + ControlSoftware.cia));

                        insertartransaccion("" + Productos.getValueAt(Productos.getSelectedRow(), 0), "5", Double.parseDouble(bd.valor("select existencia from producto where idproducto=" + producto_a_rebajar[i])), -Double.parseDouble("" + qty), Double.parseDouble(bd.valor("select existencia from producto where idproducto=" + producto_a_rebajar[i])) - Double.parseDouble("" + qty), "" + producto_a_rebajar[i]);

                        bd.EjecutarConsultas("update producto set existencia=existencia-" + qty + " where idproducto=" + producto_a_rebajar[i] + " and cia=" + ControlSoftware.cia);
                    }
                    bd.EjecutarConsultas("update detalle_devolucion set precio=0.0, isv=0.0, subtotal=0.0, total=0.0, estado=0 where id_devolucion=" + id_devolucion + " and cia=" + ControlSoftware.cia);
                    bd.EjecutarConsultas("update devoluciones set subtotal=0.0, isv=0.0, total=0.0, estado=0, observacion='" + motivo_anulacion + "', idusuario=" + ControlSoftware.us + " where id_devolucion=" + id_devolucion);
                    String n_nc = bd.valor("select n_devolucion from devoluciones where id_devolucion=" + id_devolucion + " and cia=" + ControlSoftware.cia);

                    ///////////////////ojo!!!! código riesgoso pendiente de mejora.
                    String recibo = bd.valor("select id_recibo from recibopago where numero_recibo=" + n_nc + " and tipo='" + tipon + "' and cia=" + ControlSoftware.cia);
                    bd.EjecutarConsultas("update recibopago set total=0.0, estado=0 where id_recibo=" + recibo);
                    bd.EjecutarConsultas("update detalle_recibopago set abono=0, nuevosaldo=saldoanterior, estado=0 where idrecibo=" + recibo + " and cia=" + ControlSoftware.cia);
                    bd.EjecutarConsultas("update recibopago_datos set estado=0, observacion='"+"anulado por: "+ ControlSoftware.us+", "+LocalDateTime.now()+"' where idrecibo=" + recibo + " and cia=" + ControlSoftware.cia);
                    jButton1.doClick();
                    /////////////////////////////////////////// 

                    try {
                        BaseDeDatos con = new BaseDeDatos();
                        Connection conn = con.getConexion();
                        String path = "/comprobanteanulacion_nc.jasper";
                        InputStream inputStream = getClass().getResourceAsStream(path);
                        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);

                        Map<String, Object> parametros = new HashMap<>();
                        parametros.put("factura", id_devolucion);
                        parametros.put("user", ControlSoftware.cia);
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);

                        // Crear el objeto JasperViewer y mostrar el reporte en pantalla
                        JasperViewer viewer = new JasperViewer(jasperPrint, false);
                        viewer.setVisible(true);

                    } catch (JRException ex) {
                        System.out.println("Error al generar el reporte: " + ex.getMessage());
                    }
                    JOptionPane.showMessageDialog(null, "Devolución anulada exitosamente.");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public void insertartransaccion(String id, String tipo, Double saldoactual, Double cantidad, Double saldo_final, String producto) {
        bd.EjecutarConsultas("INSERT INTO `kardex`(`fecha`, `id_documento`, `tipo_documento`, `saldo_actual`, `cantidad`, `saldo_final`, `id_producto`, `cia`, `idusuario`, `estado`) VALUES ('" + LocalDateTime.now() + "','" + id + "','" + tipo + "','" + saldoactual + "','" + cantidad + "','" + saldo_final + "','" + producto + "','" + ControlSoftware.cia + "','" + ControlSoftware.us + "','1')");
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        String perm = "91";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permitido eliminar notas de crédito.");
            return;
        }
        try {
            String f = "" + Productos.getValueAt(Productos.getSelectedRow(), 0);
            int x = 0;

            String g = bd.valor("select estado from devoluciones where id_devolucion=" + f + " and cia=" + ControlSoftware.cia);
            String factura = bd.valor("select id_factura from devoluciones where id_devolucion=" + f + " and cia=" + ControlSoftware.cia);
            String tf = bd.valor("select tipo from factura where idfactura=" + factura + " and cia=" + ControlSoftware.cia);
            String num = bd.valor("select n_devolucion from devoluciones where id_devolucion=" + f + " and cia=" + ControlSoftware.cia);
            String tn = "1";
            if (tf.equals("0")) {
                tn = "3";
            }
            String recibo = bd.valor("select id_recibo from recibopago where numero_recibo=" + num + " and tipo='" + tn + "' and cia=" + ControlSoftware.cia);

            if (g.equals("0")) {
                x = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar esta devolucion?");
                if (x == 0) {
                    bd.EjecutarConsultas("delete from detalle_recibopago where idrecibo=" + recibo + " and cia=" + ControlSoftware.cia);
                    bd.EjecutarConsultas("delete from recibopago where id_recibo=" + recibo + " and cia=" + ControlSoftware.cia);
                    bd.EjecutarConsultas("delete from detalle_devolucion where id_devolucion=" + f + " and cia=" + ControlSoftware.cia);
                    bd.EjecutarConsultas("delete from devoluciones where id_devolucion=" + f + " and cia=" + ControlSoftware.cia);
                    JOptionPane.showMessageDialog(null, "Documento eliminado.");
                    jButton1.doClick();
                }
            } else {
                JOptionPane.showMessageDialog(null, "no se puede eliminar un documento sin previa anulación.");
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mantenimiento_ventas l1 = new mantenimiento_ventas();
        Dimension internalFrameSize = l1.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        l1.setLocation((screenSize.width - internalFrameSize.width) / 2,
                (screenSize.height - internalFrameSize.height) / 2);
        DESKSOFTWARE.escritorio.add(l1);
        l1.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
         String perm = "120";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permitido imprimir notas de crédito.");
            return;
        }
        try {

            //String id_dev = "" + Productos.getValueAt(selected, 0);
            if (Productos.getValueAt(Productos.getSelectedRow(), 3).equals("CP")) {
                try {
                    NumeroEnLetras n = new NumeroEnLetras();
                    BaseDeDatos con = new BaseDeDatos();
                    Connection conn = con.getConexion();
                    // Cargar el reporte desde el archivo .jasper
                    String path = "/nc_proforma.jasper";
                    InputStream inputStream = getClass().getResourceAsStream(path);
                    JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);
                    // Crear el objeto JasperPrint con los datos y el reporte
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("factura", Productos.getValueAt(Productos.getSelectedRow(), 0));
                    parametros.put("MONTO", n.Convertir("" + Productos.getValueAt(Productos.getSelectedRow(), 7), true));
                    parametros.put("cia", ControlSoftware.cia);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);

                    // Crear el objeto JasperViewer y mostrar el reporte en pantalla
                    JasperViewer viewer = new JasperViewer(jasperPrint, false);
                    viewer.setVisible(true);

                } catch (JRException ex) {
                    System.out.println("Error al generar el reporte: " + ex.getMessage());
                }
            } else {
                try {
                    NumeroEnLetras n = new NumeroEnLetras();

                    BaseDeDatos con = new BaseDeDatos();
                    Connection conn = con.getConexion();
                    // Cargar el reporte desde el archivo .jasper
                    String path = "/nc_original.jasper";
                    InputStream inputStream = getClass().getResourceAsStream(path);
                    JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);
                    // Crear el objeto JasperPrint con los datos y el reporte
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("factura", Productos.getValueAt(Productos.getSelectedRow(), 0));
                    parametros.put("MONTO", n.Convertir("" + Productos.getValueAt(Productos.getSelectedRow(), 7), true));
                    parametros.put("cia", ControlSoftware.cia);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);

                    // Crear el objeto JasperViewer y mostrar el reporte en pantalla
                    JasperViewer viewer = new JasperViewer(jasperPrint, false);
                    viewer.setVisible(true);

                } catch (JRException ex) {
                    System.out.println("Error al generar el reporte: " + ex.getMessage());
                }
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_devoluciones_ctd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_devoluciones_ctd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_devoluciones_ctd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_devoluciones_ctd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mantenimiento_devoluciones_ctd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Productos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cliente;
    private com.toedter.calendar.JDateChooser dfecha;
    private javax.swing.JTextField dnumero;
    private com.toedter.calendar.JDateChooser hfecha;
    private javax.swing.JTextField hnumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ninguno;
    private javax.swing.JRadioButton pcliente;
    private javax.swing.JRadioButton pfecha;
    private javax.swing.JRadioButton pnumero;
    private javax.swing.JRadioButton todos;
    // End of variables declaration//GEN-END:variables
}
