/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controlsoftware;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class OC extends javax.swing.JInternalFrame {

    /**
     * Creates new form Productos
     */
    int selected = 1;
    BaseDeDatos bd = new BaseDeDatos();

    public OC() {
        super("Usuario: " + new BaseDeDatos().valor("select user from usuario where cod_user=" + ControlSoftware.us) + ", Sucursal: " + new BaseDeDatos().valor("select company from company where id_company=" + ControlSoftware.cia));

        UIManager.put("TableHeaderUI", "javax.swing.plaf.basic.BasicTableHeaderUI");
        initComponents();

        bd.LlenarTabla("select o.id_ordencompra as ID, o.nfactura as FACTURA, p.proveedor as PROVEEDOR, CASE o.metodopago WHEN '1' THEN 'CONTADO' WHEN '0' THEN 'CREDITO' END as METODO_PAGO, o.fecha_ingreso as FECHA_INGRESO, o.plazo as PLAZO, o.total_lemp as TOTAL, o.observacion as OBSERVACION, CASE o.estado WHEN '1' THEN 'GUARDADA' WHEN '2' THEN 'INGRESADA' WHEN '0' THEN 'ANULADA' END AS ESTADO  from ordencompra as o inner join proveedor as p on p.idproveedor=o.id_proveedor where o.cia=" + ControlSoftware.cia, Productos);
        Productos.setDefaultRenderer(Object.class, new MiRendererOC());
        //jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh72.png")));
//        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add72.png")));
//        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura.png")));
//        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel72.png")));
//        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar72.png")));
//        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer72.png")));
//        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show72.png")));
//        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit72.png")));
//        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back72.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        d = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        h = new com.toedter.calendar.JDateChooser();
        fecha = new javax.swing.JRadioButton();
        ninguno = new javax.swing.JRadioButton();
        ambos = new javax.swing.JRadioButton();
        proveedor = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANTENIMIENTO DE ÓRDENES DE COMPRA");

        jScrollPane1.setAutoscrolls(true);

        Productos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Productos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Productos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        Productos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Productos.getTableHeader().setReorderingAllowed(false);
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Productos);

        jPanel1.setBackground(new java.awt.Color(195, 180, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "FILTROS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DESDE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("HASTA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PROVEEDOR");

        fecha.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(fecha);
        fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setText("POR FECHA");

        ninguno.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(ninguno);
        ninguno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ninguno.setForeground(new java.awt.Color(0, 0, 0));
        ninguno.setSelected(true);
        ninguno.setText("NINGUNO");

        ambos.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(ambos);
        ambos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ambos.setForeground(new java.awt.Color(0, 0, 0));
        ambos.setText("AMBOS");

        proveedor.setBackground(new java.awt.Color(195, 180, 225));
        buttonGroup1.add(proveedor);
        proveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proveedor.setForeground(new java.awt.Color(0, 0, 0));
        proveedor.setText("POR PROVEEDOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(p))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(ninguno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ambos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ninguno)
                    .addComponent(proveedor))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha)
                    .addComponent(ambos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(195, 180, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back24.png"))); // NOI18N
        jButton6.setText("REGRESAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print24.png"))); // NOI18N
        jButton5.setText("IMPRIMIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DOIT.png"))); // NOI18N
        jButton8.setText("PROCESAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel24.png"))); // NOI18N
        jButton3.setText("ANULAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete24.png"))); // NOI18N
        jButton4.setText("ELIMINAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit24.png"))); // NOI18N
        jButton9.setText("MODIFICAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add24.png"))); // NOI18N
        jButton2.setText("NUEVA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh24.png"))); // NOI18N
        jButton1.setText("REFRESCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("CONTROLSOFTWARE - COPYRIGHT 2023 - ING. JUNIOR MORALES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String perm = "47";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permiso de ingresar ordenes de compra.");
            return;
        }
        OrdenCompra l = new OrdenCompra();
        Dimension internalFrameSize = l.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        l.setLocation((screenSize.width - internalFrameSize.width) / 2,
                (screenSize.height - internalFrameSize.height) / 2);
        DESKSOFTWARE.escritorio.add(l);
        l.show();

        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            Date date1;
            date1 = d.getDate();
            Date date2;
            date2 = h.getDate();
            if (ninguno.isSelected()) {
                bd.LlenarTabla("select o.id_ordencompra as ID, o.nfactura as FACTURA, p.proveedor as PROVEEDOR,CASE o.metodopago WHEN '1' THEN 'CONTADO' WHEN '0' THEN 'CREDITO' END as METODO_PAGO, o.fecha_ingreso as FECHA_INGRESO, o.plazo as PLAZO, o.total_lemp as TOTAL, o.observacion as OBSERVACION, CASE o.estado WHEN '1' THEN 'GUARDADA' WHEN '2' THEN 'INGRESADA' WHEN '0' THEN 'ANULADA' END AS ESTADO  from ordencompra as o inner join proveedor as p on p.idproveedor=o.id_proveedor where o.cia=" + ControlSoftware.cia, Productos);
            } else if (proveedor.isSelected() && !p.getText().isEmpty()) {
                bd.LlenarTabla("select o.id_ordencompra as ID, o.nfactura as FACTURA, p.proveedor as PROVEEDOR, CASE o.metodopago WHEN '1' THEN 'CONTADO' WHEN '0' THEN 'CREDITO' END as METODO_PAGO, o.fecha_ingreso as FECHA_INGRESO, o.plazo as PLAZO, o.total_lemp as TOTAL, o.observacion as OBSERVACION, CASE o.estado WHEN '1' THEN 'GUARDADA' WHEN '2' THEN 'INGRESADA' WHEN '0' THEN 'ANULADA' END AS ESTADO  from ordencompra as o inner join proveedor as p on p.idproveedor=o.id_proveedor where o.cia=" + ControlSoftware.cia + " and p.proveedor like '%" + p.getText() + "%'", Productos);
            } else if (fecha.isSelected() && !(date1 == null) && !(date2 == null)) {
                if (date2.compareTo(date1) == -1) {
                    JOptionPane.showMessageDialog(null, "La fecha final no puede ser mayor a la inicial.");
                } else {
                    bd.LlenarTabla("select o.id_ordencompra as ID, o.nfactura as FACTURA, p.proveedor as PROVEEDOR, CASE o.metodopago WHEN '1' THEN 'CONTADO' WHEN '0' THEN 'CREDITO' END as METODO_PAGO, o.fecha_ingreso as FECHA_INGRESO, o.plazo as PLAZO, o.total_lemp as TOTAL, o.observacion as OBSERVACION, CASE o.estado WHEN '1' THEN 'GUARDADA' WHEN '2' THEN 'INGRESADA' WHEN '0' THEN 'ANULADA' END AS ESTADO  from ordencompra as o inner join proveedor as p on p.idproveedor=o.id_proveedor where o.cia=" + ControlSoftware.cia + " and o.fecha_ingreso between '" + Date_Format.format(d.getDate()) + "' and '" + Date_Format.format(h.getDate()) + "'", Productos);
                }
            } else if (ambos.isSelected() && !p.getText().isEmpty() && !d.getDate().equals("") && !h.getDate().equals("")) {
                bd.LlenarTabla("select o.id_ordencompra as ID, o.nfactura as FACTURA, p.proveedor as PROVEEDOR, CASE o.metodopago WHEN '1' THEN 'CONTADO' WHEN '0' THEN 'CREDITO' END as METODO_PAGO, o.fecha_ingreso as FECHA_INGRESO, o.plazo as PLAZO, o.total_lemp as TOTAL, o.observacion as OBSERVACION, CASE o.estado WHEN '1' THEN 'GUARDADA' WHEN '2' THEN 'INGRESADA' WHEN '0' THEN 'ANULADA' END AS ESTADO  from ordencompra as o inner join proveedor as p on p.idproveedor=o.id_proveedor where o.cia=" + ControlSoftware.cia + " and o.fecha_ingreso between '" + Date_Format.format(d.getDate()) + "' and '" + Date_Format.format(h.getDate()) + "' and p.proveedor like '%" + p.getText() + "%'", Productos);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String perm = "50";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permiso de anular ordenes de compra.");
            return;
        }
        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        if (Productos.getValueAt(Productos.getSelectedRow(), 8).equals("GUARDADA")) {
            bd.EjecutarConsultas("update ordencompra set estado=0 where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));
            jButton1.doClick();
// bd.LlenarTabla("select o.id_ordencompra as ID, o.nfactura as FACTURA, p.proveedor as PROVEEDOR, CASE o.metodopago WHEN '1' THEN 'CONTADO' WHEN '0' THEN 'CREDITO' END as METODO_PAGO, o.fecha_ingreso as FECHA_INGRESO, o.plazo as PLAZO, o.total_lemp as TOTAL, o.observacion as OBSERVACION, CASE o.estado WHEN '1' THEN 'GUARDADA' WHEN '2' THEN 'INGRESADA' WHEN '0' THEN 'ANULADA' END AS ESTADO  from ordencompra as o inner join proveedor as p on p.idproveedor=o.id_proveedor where o.cia=" + ControlSoftware.cia, Productos);
        } else {
            JOptionPane.showMessageDialog(null, "Esta orden de compra no puede ser anulada porque ya fue procesada");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        // TODO add your handling code here:
        int pick = Productos.getSelectedRow();

        selected = Integer.parseInt(Productos.getValueAt(pick, 0).toString());
    }//GEN-LAST:event_ProductosMouseClicked

    private void ProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMousePressed
        // TODO add your handling code here:
        int pick = Productos.getSelectedRow();

        selected = Integer.parseInt(Productos.getValueAt(pick, 0).toString());
    }//GEN-LAST:event_ProductosMousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String perm = "53";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permiso de imprimir formatos de ordenes de compra.");
            return;
        }

        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        int x = Integer.parseInt("" + Productos.getValueAt(Productos.getSelectedRow(), 0));
        seleccionarimpresionoc l = new seleccionarimpresionoc(x);
        Dimension internalFrameSize = l.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        l.setLocation((screenSize.width - internalFrameSize.width) / 2,
                (screenSize.height - internalFrameSize.height) / 2);
        DESKSOFTWARE.escritorio.add(l);
        l.show();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Inventarios l = new Inventarios();
        Dimension internalFrameSize = l.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        l.setLocation((screenSize.width - internalFrameSize.width) / 2,
                (screenSize.height - internalFrameSize.height) / 2);
        DESKSOFTWARE.escritorio.add(l);
        l.show();
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String perm = "49";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permiso de eliminar ordenes de compra.");
            return;
        }
        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        if (Productos.getValueAt(Productos.getSelectedRow(), 8).equals("ANULADA")) {
            bd.EjecutarConsultas("Delete from detalleorden where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0) + " and cia=" + ControlSoftware.cia);
            bd.EjecutarConsultas("delete from ordencompra where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0) + " and cia=" + ControlSoftware.cia);
            JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
            jButton1.doClick();

        } else {
            JOptionPane.showMessageDialog(null, "Debe anular primero para poder eliminar, o bien esta orden ha sido procesada ya.");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String perm = "52";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permiso de procesar ordenes de compra.");
            return;
        }
        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        try {

            int input = 0;
            if (Productos.getValueAt(Productos.getSelectedRow(), 8).equals("GUARDADA")) {

                int x = JOptionPane.showConfirmDialog(null, "Está seguro de ingresar la orden?, está hará efecto como entrada en inventario");
                bd.EjecutarConsultas("update ordencompra set estado=2 where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));
                if (x == 0) {
                    int cantidad = Integer.parseInt(bd.valor("select COUNT(*) FROM detalleorden WHERE id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0)));
                    System.out.println(cantidad);
                    String[] h;
                    h = bd.Llenar("select id_detalle_orden from detalleorden where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0), "id_detalle_orden");
                    String prov = bd.valor("select id_proveedor from ordencompra where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));
                    String arancel = bd.valor("select arancel from ordencompra where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));
                    String factor = bd.valor("select factor from ordencompra where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));
                    String fecha = bd.valor("select fecha_ingreso from ordencompra where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));
                    String saldo = bd.valor("select saldo from ordencompra where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));

                    for (int i = 0; i < h.length; i++) {
                        String product = bd.valor("select idproducto from detalleorden where id_detalle_orden=" + h[i]);
                        String qty = bd.valor("select cantidad from detalleorden where id_detalle_orden=" + h[i]);
                        String precioL = bd.valor("select preciopromL from detalleorden where id_detalle_orden=" + h[i]);
                        String precioD = bd.valor("select preciopromD from detalleorden where id_detalle_orden=" + h[i]);
                        String u1 = bd.valor("select u1 from detalleorden where id_detalle_orden=" + h[i]);
                        String u2 = bd.valor("select u2 from detalleorden where id_detalle_orden=" + h[i]);
                        String u3 = bd.valor("select u3 from detalleorden where id_detalle_orden=" + h[i]);
                        String u4 = bd.valor("select u4 from detalleorden where id_detalle_orden=" + h[i]);
                        String u5 = bd.valor("select u5 from detalleorden where id_detalle_orden=" + h[i]);
                        String p1 = bd.valor("select p1 from detalleorden where id_detalle_orden=" + h[i]);
                        String p2 = bd.valor("select p2 from detalleorden where id_detalle_orden=" + h[i]);
                        String p3 = bd.valor("select p3 from detalleorden where id_detalle_orden=" + h[i]);
                        String p4 = bd.valor("select p4 from detalleorden where id_detalle_orden=" + h[i]);
                        String p5 = bd.valor("select p5 from detalleorden where id_detalle_orden=" + h[i]);
                        String c = bd.valor("select preciopromL from detalleorden where id_detalle_orden=" + h[i]);
                        String u = "" + c;
                        System.out.println(product + ", " + qty + ", " + precioL + ", " + precioD + ", " + u1 + ", " + u2 + ", " + u3 + ", " + u4 + ", " + u5 + ", " + p1 + ", " + p2 + ", " + p3 + ", " + p4 + ", " + p5 + ", " + c + ", " + u);
                        String[] costoenletras1 = u.split("", 0);
                        String costoenletras = "";

                        for (int k = 0; k < costoenletras1.length; k++) {
                            if (costoenletras1[k].equals("1")) {
                                costoenletras += "F";
                            }
                            if (costoenletras1[k].equals("2")) {
                                costoenletras += "R";
                            }
                            if (costoenletras1[k].equals("3")) {
                                costoenletras += "A";
                            }
                            if (costoenletras1[k].equals("4")) {
                                costoenletras += "N";
                            }
                            if (costoenletras1[k].equals("5")) {
                                costoenletras += "K";
                            }
                            if (costoenletras1[k].equals("6")) {
                                costoenletras += "L";
                            }
                            if (costoenletras1[k].equals("7")) {
                                costoenletras += "I";
                            }
                            if (costoenletras1[k].equals("8")) {
                                costoenletras += "H";
                            }
                            if (costoenletras1[k].equals("9")) {
                                costoenletras += "E";
                            }
                            if (costoenletras1[k].equals("0")) {
                                costoenletras += "C";
                            }
                            if (costoenletras1[k].equals(".")) {
                                costoenletras += ".";
                            }
                        }
                        insertartransaccion("" + Productos.getValueAt(Productos.getSelectedRow(), 0), "1", Double.parseDouble(bd.valor("select existencia from producto where idproducto=" + product)), Double.parseDouble(qty), Double.parseDouble(bd.valor("select existencia from producto where idproducto=" + product)) + Double.parseDouble(qty), "" + product);
                        bd.EjecutarConsultas("update producto set existencia=existencia+" + qty + ", preciocompra=" + precioL + ", idproveedor=" + prov + ", factor=" + factor + ", arancel=" + arancel + ", preciocompradolares=" + precioD + ", utilidad1=" + u1 + ", precio1=" + p1 + ", utilidad2=" + u2 + ", precio2=" + p2 + ", utilidad3=" + u3 + ", precio3=" + p3 + ", utilidad4=" + u4 + ", precio4=" + p4 + ", utilidad5=" + u5 + ", precio5=" + p5 + ", costoenletras='" + costoenletras + "', ultimacompra='" + fecha + "' where idproducto=" + product);

                    }
                    String comp = bd.valor("select metodopago from ordencompra where id_ordencompra=" + Productos.getValueAt(Productos.getSelectedRow(), 0));

                    if (!comp.equals("1")) {
                        bd.EjecutarConsultas("update proveedor set saldo=saldo+" + saldo);
                    }
                    input = JOptionPane.showConfirmDialog(null, "Imprimir Formato para vendedores?");
                    if (input == 0) {
                        try {
                            NumeroEnLetras n = new NumeroEnLetras();
                            BaseDeDatos con = new BaseDeDatos();
                            Connection conn = con.getConexion();
                            // Cargar el reporte desde el archivo .jasper
                            String path = "/PRECIOSNUEVOSORDEN.jasper";
                            InputStream inputStream = getClass().getResourceAsStream(path);
                            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);
                            Map<String, Object> parametros = new HashMap<>();
                            parametros.put("orden", Productos.getValueAt(Productos.getSelectedRow(), 0));
                            parametros.put("cia", ControlSoftware.cia);

                            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);
                            JasperViewer viewer = new JasperViewer(jasperPrint, false);
                            viewer.setVisible(true);

                        } catch (JRException ex) {
                            System.out.println("Error al generar el reporte: " + ex.getMessage());
                        }

                    }

                    input = JOptionPane.showConfirmDialog(null, "Imprimir Formato para corroborar entrada?");
                    if (input == 0) {
                       try {
                            NumeroEnLetras n = new NumeroEnLetras();
                            BaseDeDatos con = new BaseDeDatos();
                            Connection conn = con.getConexion();
                            // Cargar el reporte desde el archivo .jasper
                            String path = "/corroborarentradapororden.jasper";
                            InputStream inputStream = getClass().getResourceAsStream(path);
                            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);
                            Map<String, Object> parametros = new HashMap<>();
                            parametros.put("orden", Productos.getValueAt(Productos.getSelectedRow(), 0));
                            parametros.put("cia", ControlSoftware.cia);

                            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);
                            JasperViewer viewer = new JasperViewer(jasperPrint, false);
                            viewer.setVisible(true);

                        } catch (JRException ex) {
                            System.out.println("Error al generar el reporte: " + ex.getMessage());
                        }
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Esta orden ya fue procesada y cargada a inventario.");
            }
        } catch (Exception e) {
        }
        jButton1.doClick();
    }//GEN-LAST:event_jButton8ActionPerformed
    public void insertartransaccion(String id, String tipo, Double saldoactual, Double cantidad, Double saldo_final, String producto) {
        bd.EjecutarConsultas("INSERT INTO `kardex`(`fecha`, `id_documento`, `tipo_documento`, `saldo_actual`, `cantidad`, `saldo_final`, `id_producto`, `cia`, `idusuario`, `estado`) VALUES ('" + LocalDateTime.now() + "','" + id + "','" + tipo + "','" + saldoactual + "','" + cantidad + "','" + saldo_final + "','" + producto + "','" + ControlSoftware.cia + "','" + ControlSoftware.us + "','1')");
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String perm = "48";
        if (!bd.versiesta("select * from role_usuario inner join role on role.id=role_usuario.roleid inner join usuario on usuario.cod_user=role_usuario.usuarioid inner join role_permiso on role_permiso.roleid=role.id inner join permisos on permisos.id=role_permiso.permisoid where permisos.id=" + perm + " and role_usuario.cia=" + ControlSoftware.cia + " and usuario.cod_user=" + ControlSoftware.us)) {
            JOptionPane.showMessageDialog(null, "Usted no tiene permiso de modificar ordenes de compra.");
            return;
        }
        if (Productos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }

        if (Productos.getValueAt(Productos.getSelectedRow(), 8).equals("GUARDADA")) {
            ModificarOC l = new ModificarOC(Integer.parseInt("" + Productos.getValueAt(Productos.getSelectedRow(), 0)));
            Dimension internalFrameSize = l.getSize();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            l.setLocation((screenSize.width - internalFrameSize.width) / 2,
                    (screenSize.height - internalFrameSize.height) / 2);
            DESKSOFTWARE.escritorio.add(l);
            l.show();

            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Esta orden de compra no puede ser modificada");
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Productos;
    private javax.swing.JRadioButton ambos;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser d;
    private javax.swing.JRadioButton fecha;
    private com.toedter.calendar.JDateChooser h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton ninguno;
    private javax.swing.JTextField p;
    private javax.swing.JRadioButton proveedor;
    // End of variables declaration//GEN-END:variables
}
