/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controlsoftware;


import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class pagocontado extends javax.swing.JInternalFrame {

    /**
     * Creates new form formato
     */
    int selected = -1;
    BaseDeDatos bd = new BaseDeDatos();
    DefaultTableModel modelo;

    public pagocontado(double monto) {
        super("Usuario: " + new BaseDeDatos().valor("select user from usuario where cod_user=" + ControlSoftware.us) + ", Sucursal: " + new BaseDeDatos().valor("select company from company where id_company=" + ControlSoftware.cia));

        initComponents();

        modelo = (DefaultTableModel) recibos.getModel();
        jCheckBox1.setVisible(false);
        referencia.setText("vacio");
        valor.setText("0.0");
        observacion.setText("vacio");
        mrecibo.setText("" + monto);
        mrestante.setText("" + monto);
        magregado.setText("" + 0.0);
        bd.LlenarCombo1("select idbanco, nombre from banco where cia=" + ControlSoftware.cia, banco, "idbanco", "nombre");
        Item ban = (Item) banco.getSelectedItem();
        bd.LlenarCombo1("select id_cuenta, n_cuenta from cuenta where cia=" + ControlSoftware.cia + " and id_banco=" + ban.getId(), cuenta, "id_cuenta", "n_cuenta");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        referencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        codpago = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        banco = new javax.swing.JComboBox<>();
        cuenta = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        recibos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        mrecibo = new javax.swing.JTextField();
        magregado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mrestante = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DESCRIPCIÓN DE PAGO CONTADO");

        jPanel6.setBackground(new java.awt.Color(195, 180, 225));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "DATOS DE CONTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("REFERENCIA");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("VALOR");

        valor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorMouseClicked(evt);
            }
        });
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorKeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("ELIMINAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("MODIFICAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TIPO PAGO");

        codpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEPOSITO", "CHEQUE", "EFECTIVO", "TARJETA", "TRANSFERENCIA" }));

        observacion.setColumns(20);
        observacion.setRows(5);
        jScrollPane3.setViewportView(observacion);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("OBSERVACIÓN");

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("BANCO");

        banco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bancoItemStateChanged(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("CUENTA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel21)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(banco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codpago, 0, 227, Short.MAX_VALUE)
                            .addComponent(valor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel22))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(referencia)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 126, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jButton8)
                        .addGap(125, 125, 125))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(codpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(195, 180, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back24.png"))); // NOI18N
        jButton4.setText("REGRESAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save24.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        recibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO PAGO", "REFERENCIA", "BANCO", "NCUENTA", "VALOR", "OBSERVACION"
            }
        ));
        recibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recibosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(recibos);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("MONTO DEL RECIBO");

        mrecibo.setEditable(false);

        magregado.setEditable(false);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("MONTO AGREGADO");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("MONTO RESTANTE");

        mrestante.setEditable(false);

        jCheckBox1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("HABILITADO");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2))
                            .addComponent(mrecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(magregado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox1)
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel17))
                            .addComponent(mrestante, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mrecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mrestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONTROLSOFTWARE - COPYRIGHT 2023 - ING. JUNIOR MORALES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 8) {
            if (valor.getText().isEmpty()) {
                valor.setText("0.0");

            }
        }
    }//GEN-LAST:event_valorKeyReleased

    private void valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        if (!(key == '0' || key == '1' || key == '2' || key == '3' || key == '4' || key == '5' || key == '6' || key == '7' || key == '8' || key == '9' || key == '.') || (key == '.' && valor.getText().contains("."))) {

            evt.consume();
        }

    }//GEN-LAST:event_valorKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((Double.parseDouble(mrestante.getText()) < Double.parseDouble(valor.getText())) == true) {
                JOptionPane.showMessageDialog(null, "El pago no puede ser mayor que el monto restante");
                return;
            }
            if (Double.parseDouble(valor.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "El monto no puede ser 0");
            } else {
                if (observacion.getText().isEmpty()) {
                    observacion.setText("no contiene");
                }
                Item ba = (Item) banco.getSelectedItem();
                Item ct = (Item) cuenta.getSelectedItem();
                Object[] fila = new Object[6];
                fila[0] = codpago.getSelectedIndex();
                fila[1] = referencia.getText();
                fila[2] = ba.getId();
                fila[3] = ct.getId();
                fila[4] = valor.getText();
                fila[5] = observacion.getText();
                modelo.addRow(fila);
                magregado.setText("" + (Double.parseDouble(magregado.getText()) + Double.parseDouble(valor.getText())));
                mrestante.setText("" + (Double.parseDouble("" + mrecibo.getText()) - Double.parseDouble("" + magregado.getText())));
                referencia.setText("vacio");
                valor.setText("0.0");
                observacion.setText("vacio");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (recibos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        selected = recibos.getSelectedRow();
        if (selected == -1)
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila que eliminar");
        else {
            magregado.setText("" + (Double.parseDouble(magregado.getText()) - Double.parseDouble("" + recibos.getValueAt(selected, 4))));
            mrestante.setText("" + (Double.parseDouble(mrestante.getText()) + Double.parseDouble("" + recibos.getValueAt(selected, 4))));
            referencia.setText("vacio");
            valor.setText("0.0");
            observacion.setText("vacio");
            modelo.removeRow(selected);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (recibos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Ninguna fila seleccionada!");
            return;
        }
        selected = recibos.getSelectedRow();
        if (selected == -1)
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila que MODIFICAR");
        else {
            codpago.setSelectedIndex(Integer.parseInt("" + recibos.getValueAt(selected, 0)));
            referencia.setText("" + recibos.getValueAt(selected, 1));
            bd.seleccionarItemPorId(banco, "" + recibos.getValueAt(selected, 2));
            bd.seleccionarItemPorId(cuenta, "" + recibos.getValueAt(selected, 3));
            valor.setText("" + recibos.getValueAt(selected, 4));
            observacion.setText("" + recibos.getValueAt(selected, 5));
            modelo.removeRow(selected);

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (ingresarfactura.pedido.equals("0")) {
            for (int i = 0; i < ingresarfactura.detalle.getRowCount(); i++) {
                Double q = Double.parseDouble(bd.valor("select existencia-reserva from producto where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0) + " and cia=" + ControlSoftware.cia));
                Double qp = Double.parseDouble("" + ingresarfactura.detalle.getValueAt(i, 3));
                if (q < qp) {
                    JOptionPane.showMessageDialog(null, "Favor modificar cantidad del producto:" + "" + ingresarfactura.detalle.getValueAt(i, 1) + ", la existencia cambió..");
                    return;
                }
            }
        }
        if (!ingresarfactura.pedido.equals("0")) {//si viene de pedido
            String codproductoreservado[] = bd.Llenar("select idproducto from detalle_orden_de_pedido where id_orden_de_pedido=" + ingresarfactura.pedido + " and cia=" + ControlSoftware.cia, "idproducto");
            String canproductoreservado[] = bd.Llenar("select cantidad from detalle_orden_de_pedido where id_orden_de_pedido=" + ingresarfactura.pedido + " and cia=" + ControlSoftware.cia, "cantidad");
            for (int i = 0; i < codproductoreservado.length; i++) {
                for (int j = 0; j < ingresarfactura.detalle.getRowCount(); j++) {
                    if ((""+ingresarfactura.detalle.getValueAt(j, 0)).equals(codproductoreservado[i])) {//si la fila contiene el mismo codigo con un registro de tabla
                        if (Double.parseDouble("" + ingresarfactura.detalle.getValueAt(j, 3)) > Double.parseDouble(canproductoreservado[i])) {//si pedimos mas que lo reservado pasa esto revisamos existencia
                            Double q = Double.parseDouble(bd.valor("select existencia-reserva from producto where idproducto=" + codproductoreservado[i] + " and cia=" + ControlSoftware.cia));
                            Double qp = Double.parseDouble("" + ingresarfactura.detalle.getValueAt(j, 3)) - Double.parseDouble(canproductoreservado[i]);
                            if (q < qp) {
                                JOptionPane.showMessageDialog(null, "Favor modificar cantidad del producto:" + "" + ingresarfactura.detalle.getValueAt(j, 1) + ", la existencia cambió. uwu");
                                return;
                            }
                        }
                    }

                }
            }
            for (int i = 0; i < ingresarfactura.detalle.getRowCount(); i++) {
                int x = 1;
                for (int j = 0; j < codproductoreservado.length; j++) {
                    if ((""+ingresarfactura.detalle.getValueAt(i, 0)).equals(codproductoreservado[j])) {//si la fila contiene el mismo codigo con un registro de tabla
                        x = 0;
                    }
                }
                if (x == 1) {
                    Double q = Double.parseDouble(bd.valor("select existencia-reserva from producto where idproducto=" +ingresarfactura. detalle.getValueAt(i, 0) + " and cia=" + ControlSoftware.cia));
                    Double qp = Double.parseDouble("" + ingresarfactura.detalle.getValueAt(i, 3));
                    if (q < qp) {
                        JOptionPane.showMessageDialog(null, "Favor modificar cantidad del producto:" + "" + ingresarfactura.detalle.getValueAt(i, 1) + ", la existencia cambió. uwus");
                        return;
                    }
                }
            }

        }

        if (mrestante.getText().equals("0.0")) {
            int l = 0;

            if (ingresarfactura.original.isSelected()) {
                l = 1;
            }
            LocalDate date = LocalDate.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            double sal = Double.parseDouble(ingresarfactura.total.getText().replace(",", ""));
            int opc = 0;
            opc = JOptionPane.showConfirmDialog(null, "Desea guardar la factura con el siguiente numero: " + ingresarfactura.factura.getText() + "?");
            if (opc == 0) {
                String st = ingresarfactura.subtotal.getText().replace(",", "");
                String im = ingresarfactura.isv.getText().replace(",", "");
                String t = ingresarfactura.total.getText().replace(",", "");
                String tt = ingresarfactura.totalfinal.getText().replace(",", "");
                String des = ingresarfactura.descuento.getText().replace(",", "");
                System.out.println(st);
                System.out.println(im);
                System.out.println(t);
                Item ve = (Item) ingresarfactura.vend.getSelectedItem();
                String caf = bd.valor("select  caiid from company where id_company=" + ControlSoftware.cia);
                String cf = bd.doble("INSERT INTO `factura`(`numerofactura`, `tipo`, `cia`, `idcliente`, `idvendedor`, `subtotal`, `isv`, `total`, `fechafactura`, `fechaingreso`, `saldo`, `idusuario`, `observacion`, `condicionpago`, `transporte`, `guia`, `estado`, `comprobado`, `op`, `caiid`, `cajaid`, `totalfinal`, `descuento`, `fechapago`) VALUES ('" + ingresarfactura.factura.getText() + "','" + l + "','" + ControlSoftware.cia + "','" + ingresarfactura.codcliente.getText() + "','" + ve.getId() + "','" + st + "','" + im + "','" + t + "','" + Date_Format.format(ingresarfactura.fecha.getDate()) + "','" + date.format(formatter) + "','" + "0.0" + "','" + ControlSoftware.us + "','" + ingresarfactura.obsfact.getText() + "','" + 1 + "','0','pendiente','3','0','" + ingresarfactura.pedido + "', '" + caf + "','" + bd.valor("select id from caja where idusuario=" + ControlSoftware.us + " and cia=" + ControlSoftware.cia + " and estado=1") + "','" + tt + "','" + des + "','"+date.format(formatter)+"')", "SELECT @@IDENTITY AS 'id'");
                System.out.println(cf);
                for (int i = 0; i < ingresarfactura.detalle.getRowCount(); i++) {
                    String v = bd.valor("select precio1 from producto where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0));
                    bd.EjecutarConsultas("INSERT INTO `detalle_factura`(`idfactura`, `idproducto`, `cantidad`, `preciounitario`, `preciovendido`, `costo`, `total`, `fechadetalle`, `idusuario`, `observacion`, `estado`, `cia`) VALUES ('" + cf + "','" + ingresarfactura.detalle.getValueAt(i, 0) + "','" + ingresarfactura.detalle.getValueAt(i, 3) + "','" + v + "','" + ingresarfactura.detalle.getValueAt(i, 5) + "','" + ingresarfactura.detalle.getValueAt(i, 4) + "','" + ingresarfactura.detalle.getValueAt(i, 6) + "','" + date.format(formatter) + "','" + ControlSoftware.us + "','" + ingresarfactura.detalle.getValueAt(i, 7) + "','1','" + ControlSoftware.cia + "')");

                    insertartransaccion(cf, "2", Double.parseDouble(bd.valor("select existencia from producto where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0))), -Double.parseDouble("" + ingresarfactura.detalle.getValueAt(i, 3)), Double.parseDouble(bd.valor("select existencia from producto where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0))) - Double.parseDouble("" + ingresarfactura.detalle.getValueAt(i, 3)), "" + ingresarfactura.detalle.getValueAt(i, 0));

                    bd.EjecutarConsultas("update producto set existencia=existencia-" + ingresarfactura.detalle.getValueAt(i, 3) + " where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0));
                    if (!ingresarfactura.pedido.equals("0")) {
                        if (bd.versiesta("select idproducto from detalle_orden_de_pedido where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0) + " and id_orden_de_pedido=" + ingresarfactura.pedido + " and cia=" + ControlSoftware.cia)) {
                            bd.EjecutarConsultas("update producto set reserva=reserva-" + bd.valor("select cantidad from detalle_orden_de_pedido where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0) + " and id_orden_de_pedido=" + ingresarfactura.pedido + " and cia=" + ControlSoftware.cia) + " where idproducto=" + ingresarfactura.detalle.getValueAt(i, 0));
                        }
                    }

                }
                try {

                    String yt = "";
                    if (bd.valor("select MAX(cast(numero_recibo as unsigned))+1 from recibopago where tipo=2 and cia=" + ControlSoftware.cia) == null) {
                        yt = "1";
                    } else {
                        yt = String.format("%.0f", (Double.parseDouble(bd.valor("select MAX(cast(numero_recibo as unsigned))+1 from recibopago where tipo=2 and cia=" + ControlSoftware.cia))));
                    }
                    String v = bd.doble("INSERT INTO `recibopago`(`numero_recibo`, `tipo`, `fecha`, `descripcion`, `idcliente`, `idvendedor`, `cia`, `total`, `fechaingreso`, `estado`) VALUES ('" + yt + "','" + 2 + "','" + Date_Format.format(ingresarfactura.fecha.getDate()) + "','" + "pago de factura contado, recibo interno" + "','" + ingresarfactura.codcliente.getText() + "','" + ve.getId() + "','" + ControlSoftware.cia + "','" + t + "','" + Date_Format.format(ingresarfactura.fecha.getDate()) + "','1')", "SELECT @@IDENTITY AS 'id'");

                    bd.EjecutarConsultas("INSERT INTO `detalle_recibopago`(`idrecibo`, `idfactura`, `abono`, `saldoanterior`, `nuevosaldo`, `cia`, `estado`, `fechasistema`) VALUES ('" + v + "','" + cf + "','" + t + "','" + t + "','" + 0 + "','" + ControlSoftware.cia + "','1','" + Date_Format.format(ingresarfactura.fecha.getDate()) + "')");

//                    Object[] fila = new Object[6];
//                    for (int i = 0; i < recibos.getRowCount(); i++) {
//                        for (int j = 0; j < 6; j++) {
//                            fila[j] = recibos.getValueAt(i, j);
//                        }
//                        Item ban = (Item) banco.getSelectedItem();
//                        Item ct = (Item) cuenta.getSelectedItem();
//                        bd.EjecutarConsultas("INSERT INTO `recibopago_datos`(`idrecibo`, `tipo`, `referencia`, `id_banco`, `id_cuenta`, `observacion`, `estado`, `cia`, `monto`) VALUES ('" + v + "','" + codpago.getSelectedIndex() + "','" + referencia.getText() + "','" + ban.getId() + "','" + ct.getId() + "','" + "recibo de contado factura: " + ingresarfactura.factura.getText() + "','1','" + ControlSoftware.cia + "')");
//                    }
                    for (int i = 0; i < recibos.getRowCount(); i++) {
                        bd.EjecutarConsultas("INSERT INTO `recibopago_datos`(`idrecibo`, `tipo`, `referencia`, `id_banco`, `id_cuenta`, `observacion`, `estado`, `cia`, `monto`, `fecha`, `fecha_sistema`) VALUES ('" + v + "','" + recibos.getValueAt(i, 0) + "','" + recibos.getValueAt(i, 1) + "','" + recibos.getValueAt(i, 2) + "','" + recibos.getValueAt(i, 3) + "','" + recibos.getValueAt(i, 5) + "','1','" + ControlSoftware.cia + "','" + recibos.getValueAt(i, 4) + "','" + Date_Format.format(ingresarfactura.fecha.getDate()) + "','" + LocalDateTime.now() + "')");
                    }
                    if (!ingresarfactura.pedido.equals("0")) {
                        bd.EjecutarConsultas("update orden_de_pedido set estado=2 where idorden=" + ingresarfactura.pedido);
                    }
                    dispose();
                    ingresarfactura.jButton5.doClick();

                    try {
                        BaseDeDatos con = new BaseDeDatos();
                        Connection conn = con.getConexion();
                        // Cargar el reporte desde el archivo .jasper
                        String path = "/PagoFactura.jasper";
                        InputStream inputStream = getClass().getResourceAsStream(path);
                        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);

                        // Crear el objeto JasperPrint con los datos y el reporte
                        Map<String, Object> parametros = new HashMap<>();
                        parametros.put("id_recibo", v);
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);

                        // Crear el objeto JasperViewer y mostrar el reporte en pantalla
                        JasperViewer viewer = new JasperViewer(jasperPrint, false);
                        viewer.setVisible(true);
                    } catch (JRException ex) {
                        System.out.println("Error al generar el reporte: " + ex.getMessage());
                    }
                    if (l == 0) {
                        try {
                            NumeroEnLetras n = new NumeroEnLetras();
                            BaseDeDatos con = new BaseDeDatos();
                            Connection conn = con.getConexion();
                            // Cargar el reporte desde el archivo .jasper
                            String path = "/facturaproforma.jasper";
                            InputStream inputStream = getClass().getResourceAsStream(path);
                            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);
                            Map<String, Object> parametros = new HashMap<>();
                            parametros.put("factura", cf);
                            parametros.put("MONTO", n.Convertir(t, true));
                            parametros.put("cia", ControlSoftware.cia);
                            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);
                            JasperViewer viewer = new JasperViewer(jasperPrint, false);
                            viewer.setVisible(true);
                        } catch (JRException ex) {
                            System.out.println("Error al generar el reporte: " + ex.getMessage());
                        }
                    } else {
                        try {
                            NumeroEnLetras n = new NumeroEnLetras();
                            BaseDeDatos con = new BaseDeDatos();
                            Connection conn = con.getConexion();
                            // Cargar el reporte desde el archivo .jasper
                            String path = "/facturaoriginal.jasper";
                            InputStream inputStream = getClass().getResourceAsStream(path);
                            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);
                            Map<String, Object> parametros = new HashMap<>();
                            parametros.put("factura", cf);
                            parametros.put("MONTO", n.Convertir(t, true));
                            parametros.put("cia", ControlSoftware.cia);
                            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);
                            JasperViewer viewer = new JasperViewer(jasperPrint, false);
                            viewer.setVisible(true);
                        } catch (JRException ex) {
                            JOptionPane.showMessageDialog(null, "Error al generar el reporte: " + ex.getMessage());
                        }
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al generar el reporte: " + e.getMessage());

                }
                JOptionPane.showMessageDialog(null, "Registro guardado");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe sustentar el monto total del recibo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void insertartransaccion(String id, String tipo, Double saldoactual, Double cantidad, Double saldo_final, String producto) {
        bd.EjecutarConsultas("INSERT INTO `kardex`(`fecha`, `id_documento`, `tipo_documento`, `saldo_actual`, `cantidad`, `saldo_final`, `id_producto`, `cia`, `idusuario`, `estado`) VALUES ('" + LocalDateTime.now() + "','" + id + "','" + tipo + "','" + saldoactual + "','" + cantidad + "','" + saldo_final + "','" + producto + "','" + ControlSoftware.cia + "','" + ControlSoftware.us + "','1')");
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ingresarfactura.jCheckBox1.setSelected(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void recibosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recibosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_recibosMouseClicked

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        if (jCheckBox1.isSelected())
            this.setEnabled(true);
        else
            this.setEnabled(false);
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void bancoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bancoItemStateChanged
        // TODO add your handling code here:
        Item ban = (Item) banco.getSelectedItem();
        bd.LlenarCombo1("select id_cuenta, n_cuenta from cuenta where cia=" + ControlSoftware.cia + " and id_banco=" + ban.getId(), cuenta, "id_cuenta", "n_cuenta");
    }//GEN-LAST:event_bancoItemStateChanged

    private void valorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            valor.setText("" + mrestante.getText());
        }
    }//GEN-LAST:event_valorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagocontado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagocontado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagocontado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagocontado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagocontado(0.0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> banco;
    private javax.swing.JComboBox<String> codpago;
    private javax.swing.JComboBox<String> cuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    public static javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField magregado;
    private javax.swing.JTextField mrecibo;
    private javax.swing.JTextField mrestante;
    private javax.swing.JTextArea observacion;
    public static javax.swing.JTable recibos;
    private javax.swing.JTextField referencia;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
