/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controlsoftware;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class reportedecheques_opciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form formato
     */
    public String ustemp = "";
    BaseDeDatos bd = new BaseDeDatos();

    public reportedecheques_opciones() {
        super("Usuario: " + new BaseDeDatos().valor("select user from usuario where cod_user=" + ControlSoftware.us) + ", Sucursal: " + new BaseDeDatos().valor("select company from company where id_company=" + ControlSoftware.cia));
        initComponents();
        bd.LlenarCombo1("select idbanco, nombre from banco where cia=" + ControlSoftware.cia, banco, "idbanco", "nombre");
        Item ba = (Item) banco.getSelectedItem();
        bd.LlenarCombo1("select id_cuenta, n_cuenta from cuenta where cia=" + ControlSoftware.cia + " and id_banco=" + ba.getId(), cuenta, "id_cuenta", "n_cuenta");
        Item cue = (Item) cuenta.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnumero = new javax.swing.JRadioButton();
        pfecha = new javax.swing.JRadioButton();
        sf = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        desdefecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        hastafecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        desdenumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hastanumero = new javax.swing.JTextField();
        pbeneficiario = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        ben = new javax.swing.JTextField();
        pbanco = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        banco = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cuenta = new javax.swing.JComboBox<>();
        pcuenta = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORTES DE CHEQUES");

        jPanel1.setBackground(new java.awt.Color(195, 180, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back24.png"))); // NOI18N
        jButton4.setText("REGRESAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh24.png"))); // NOI18N
        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        pnumero.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pnumero);
        pnumero.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pnumero.setForeground(new java.awt.Color(0, 0, 0));
        pnumero.setText("POR NUMERO");

        pfecha.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pfecha);
        pfecha.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pfecha.setForeground(new java.awt.Color(0, 0, 0));
        pfecha.setText("POR FECHA");
        pfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfechaActionPerformed(evt);
            }
        });

        sf.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(sf);
        sf.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sf.setForeground(new java.awt.Color(0, 0, 0));
        sf.setSelected(true);
        sf.setText("SIN FILTRO");
        sf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(195, 180, 225));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "POR FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DESDE");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("HASTA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desdefecha, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hastafecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(desdefecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hastafecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(195, 180, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "POR NUMERO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DESDE");

        desdenumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                desdenumeroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                desdenumeroKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("HASTA");

        hastanumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hastanumeroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hastanumeroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desdenumero, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hastanumero)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(desdenumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(hastanumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pbeneficiario.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pbeneficiario);
        pbeneficiario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pbeneficiario.setForeground(new java.awt.Color(0, 0, 0));
        pbeneficiario.setText("POR BENEFICIARIO");

        jPanel7.setBackground(new java.awt.Color(195, 180, 225));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "POR BENEFICIARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ben)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(ben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pbanco.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pbanco);
        pbanco.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pbanco.setForeground(new java.awt.Color(0, 0, 0));
        pbanco.setText("POR BANCO");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("BANCO");

        banco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bancoItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CUENTA");

        pcuenta.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pcuenta);
        pcuenta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pcuenta.setForeground(new java.awt.Color(0, 0, 0));
        pcuenta.setText("POR CUENTA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(banco, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfecha)
                            .addComponent(pnumero)
                            .addComponent(pbeneficiario)
                            .addComponent(pbanco)
                            .addComponent(pcuenta)
                            .addComponent(sf))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(sf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pfecha))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnumero)
                        .addGap(11, 11, 11)
                        .addComponent(pbeneficiario))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pbanco)
                        .addGap(11, 11, 11)
                        .addComponent(pcuenta))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONTROLSOFTWARE - COPYRIGHT 2023 - ING. JUNIOR MORALES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfActionPerformed

    private void pfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opc = 0;
        String dfecha = "";
        String hfecha = "";
        String dnumero = "";
        String hnumero = "";
        String pf = "0";
        String pn = "0";
        String pb = "0";
        String beneficiario = "";
        String pba = "0";
        String pcu = "0";
        String dcue = "";
        String hcue = "";
        String dban = "";
        String hban = "";
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
        Date date1;
        date1 = desdefecha.getDate();
        Date date2;
        date2 = hastafecha.getDate();
        if (sf.isSelected()) {
            dfecha = bd.valor("select min(fecha) from cheque where cia=" + ControlSoftware.cia);
            hfecha = bd.valor("select max(fecha) from cheque where cia=" + ControlSoftware.cia);
            dnumero = bd.valor("select CAST(MIN(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            hnumero = bd.valor("select CAST(MAX(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            beneficiario = "";
            dban = bd.valor("select min(idbanco) from banco where cia=" + ControlSoftware.cia);
            hban = bd.valor("select max(idbanco) from banco where cia=" + ControlSoftware.cia);
            dcue = bd.valor("select min(idbanco) from banco where cia=" + ControlSoftware.cia);
            hcue = bd.valor("select max(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);

            pf = "0";
            pn = "0";
            pb = "0";
            pba = "0";
            pcu = "0";
        }

        if (pfecha.isSelected()) {
            if (!(date1 == null) && !(date2 == null)) {
                if (date2.compareTo(date1) == -1) {
                    JOptionPane.showMessageDialog(null, "La fecha final no puede ser mayor a la inicial.");
                    return;
                } else {
                    dfecha = "" + Date_Format.format(desdefecha.getDate());
                    hfecha = "" + Date_Format.format(hastafecha.getDate());
                    dnumero = bd.valor("select CAST(MIN(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
                    hnumero = bd.valor("select CAST(MAX(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
                    beneficiario = "";
                    dban = bd.valor("select min(idbanco) from banco where cia=" + ControlSoftware.cia);
                    hban = bd.valor("select max(idbanco) from banco where cia=" + ControlSoftware.cia);
                    dcue = bd.valor("select min(idbanco) from banco where cia=" + ControlSoftware.cia);
                    hcue = bd.valor("select max(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);

                    pf = "1";
                    pn = "0";
                    pb = "0";
                    pba = "0";
                    pcu = "0";
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las fechas son inválidas");
                return;
            }

        }
        if (pnumero.isSelected()) {
            if (desdenumero.getText().isEmpty() || hastanumero.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Los numeros son inválidos");
                return;
            }
            if (Integer.parseInt(desdenumero.getText()) > Integer.parseInt(hastanumero.getText())) {
                JOptionPane.showMessageDialog(null, "El numero final no puede ser menor");
                return;
            }
            dfecha = bd.valor("select min(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            hfecha = bd.valor("select max(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            dnumero = desdenumero.getText();
            hnumero = hastanumero.getText();
            beneficiario = "";
            dban = bd.valor("select min(idbanco) from banco where cia=" + ControlSoftware.cia);
            hban = bd.valor("select max(idbanco) from banco where cia=" + ControlSoftware.cia);
            dcue = bd.valor("select min(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);
            hcue = bd.valor("select max(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);

            pf = "0";
            pn = "1";
            pb = "0";
            pba = "0";
            pcu = "0";
        }
        if (pbeneficiario.isSelected()) {
            if (beneficiario.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe ingresar beneficiario para filtrar");
                return;
            }
            dfecha = bd.valor("select min(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            hfecha = bd.valor("select max(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            dnumero = bd.valor("select CAST(MIN(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            hnumero = bd.valor("select CAST(MAX(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            beneficiario = ben.getText();
            dban = bd.valor("select min(idbanco) from banco where cia=" + ControlSoftware.cia);
            hban = bd.valor("select max(idbanco) from banco where cia=" + ControlSoftware.cia);
            dcue = bd.valor("select min(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);
            hcue = bd.valor("select max(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);

            pf = "0";
            pn = "0";
            pb = "1";
            pba = "0";
            pcu = "0";

        }
        if (pbanco.isSelected()) {
            dfecha = bd.valor("select min(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            hfecha = bd.valor("select max(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            dnumero = bd.valor("select CAST(MIN(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            hnumero = bd.valor("select CAST(MAX(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            beneficiario = "";
            Item banc = (Item) banco.getSelectedItem();
            dban = banc.getId();
            hban = banc.getId();
            dcue = bd.valor("select min(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);
            hcue = bd.valor("select max(id_cuenta) from cuenta where cia=" + ControlSoftware.cia);
            pf = "0";
            pn = "0";
            pb = "0";
            pba = "1";
            pcu = "0";
        }
        if (pcuenta.isSelected()) {
            dfecha = bd.valor("select min(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            hfecha = bd.valor("select max(fecha) from recibopago where tipo=0 and cia=" + ControlSoftware.cia);
            dnumero = bd.valor("select CAST(MIN(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            hnumero = bd.valor("select CAST(MAX(CAST(numerocheque AS UNSIGNED)) AS UNSIGNED) from cheque where cia=" + ControlSoftware.cia);
            beneficiario = "";
            Item cuent = (Item) cuenta.getSelectedItem();

            dban = bd.valor("select min(idbanco) from banco where cia=" + ControlSoftware.cia);
            hban = bd.valor("select max(idbanco) from banco where cia=" + ControlSoftware.cia);
            dcue = cuent.getId();
            hcue = cuent.getId();
            pf = "0";
            pn = "0";
            pb = "0";
            pba = "0";
            pcu = "1";
        }
        System.out.println(dfecha);
        System.out.println(hfecha);

        try {
            BaseDeDatos con = new BaseDeDatos();
            Connection conn = con.getConexion();
            // Cargar el reporte desde el archivo .jasper
            String path = "/reportedecheques.jasper";
            InputStream inputStream = getClass().getResourceAsStream(path);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(inputStream);

            Map<String, Object> parametros = new HashMap<>();
            parametros.put("dfecha", dfecha);
            parametros.put("hfecha", hfecha);
            parametros.put("dnumero", dnumero);
            parametros.put("hnumero", hnumero);
            parametros.put("beneficiario", beneficiario);
            parametros.put("dbanco", dban);
            parametros.put("hbanco", hban);
            parametros.put("dcuenta", dcue);
            parametros.put("hcuenta", hcue);

            parametros.put("cia", ControlSoftware.cia);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setVisible(true);

        } catch (JRException ex) {
            System.out.println("Error al generar el reporte: " + ex.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ReportesClientes l = new ReportesClientes();
        Dimension internalFrameSize = l.getSize();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        l.setLocation((screenSize.width - internalFrameSize.width) / 2,
                (screenSize.height - internalFrameSize.height) / 2);
        DESKSOFTWARE.escritorio.add(l);
        l.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void desdenumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desdenumeroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_desdenumeroKeyReleased

    private void desdenumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desdenumeroKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        if (!(key == '0' || key == '1' || key == '2' || key == '3' || key == '4' || key == '5' || key == '6' || key == '7' || key == '8' || key == '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_desdenumeroKeyTyped

    private void hastanumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hastanumeroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hastanumeroKeyReleased

    private void hastanumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hastanumeroKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        if (!(key == '0' || key == '1' || key == '2' || key == '3' || key == '4' || key == '5' || key == '6' || key == '7' || key == '8' || key == '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_hastanumeroKeyTyped

    private void bancoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bancoItemStateChanged
        // TODO add your handling code here:
        Item ban = (Item) banco.getSelectedItem();
        bd.LlenarCombo1("select id_cuenta, n_cuenta from cuenta where cia=" + ControlSoftware.cia + " and id_banco=" + ban.getId(), cuenta, "id_cuenta", "n_cuenta");

    }//GEN-LAST:event_bancoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportedecheques_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportedecheques_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportedecheques_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }


        //</edithastanumeroor-fold>
        //</editor-fold>
        //</eddesdenumeroitor-fold>
        //</editodesdefechar-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>//</edithastanumeroor-fold>
        //</editor-fold>
        //</eddesdenumeroitor-fold>
        //</editodesdefechar-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */ java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportedecheques_opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> banco;
    private javax.swing.JTextField ben;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cuenta;
    private com.toedter.calendar.JDateChooser desdefecha;
    private javax.swing.JTextField desdenumero;
    private com.toedter.calendar.JDateChooser hastafecha;
    private javax.swing.JTextField hastanumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton pbanco;
    private javax.swing.JRadioButton pbeneficiario;
    private javax.swing.JRadioButton pcuenta;
    private javax.swing.JRadioButton pfecha;
    private javax.swing.JRadioButton pnumero;
    private javax.swing.JRadioButton sf;
    // End of variables declaration//GEN-END:variables
}
