/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controlsoftware;

import java.awt.Component;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Usuario
 */
public class seleccionarcliente_estado_cuenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Productos
     */
    int selected = 1;
    int y;
    BaseDeDatos bd = new BaseDeDatos();

    public seleccionarcliente_estado_cuenta() {
        super("Usuario: " + new BaseDeDatos().valor("select user from usuario where cod_user=" + ControlSoftware.us) + ", Sucursal: " + new BaseDeDatos().valor("select company from company where id_company=" + ControlSoftware.cia));

        initComponents();
        
        bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.cia=" + ControlSoftware.cia, Productos);
        
       // jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png")));
        //jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png")));
        autoajustar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        se = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        dni = new javax.swing.JRadioButton();
        nombre = new javax.swing.JRadioButton();
        rtn = new javax.swing.JRadioButton();
        activo = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        se.setEditable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SELECCIONE CLIENTE ESTADO DE CUENTA");

        jPanel2.setBackground(new java.awt.Color(195, 180, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "FILTROS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("BUSCAR");

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarKeyPressed(evt);
            }
        });

        buttonGroup1.add(dni);
        dni.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        dni.setForeground(new java.awt.Color(0, 0, 0));
        dni.setText("POR DNI");

        buttonGroup1.add(nombre);
        nombre.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setSelected(true);
        nombre.setText("POR NOMBRE");

        buttonGroup1.add(rtn);
        rtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        rtn.setForeground(new java.awt.Color(0, 0, 0));
        rtn.setText("POR RTN");

        activo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        activo.setForeground(new java.awt.Color(0, 0, 0));
        activo.setText("SOLO ACTIVOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dni)
                        .addGap(18, 18, 18)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(activo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(dni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtn)
                    .addComponent(activo))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(195, 180, 225));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back24.png"))); // NOI18N
        jButton6.setText("REGRESAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh24.png"))); // NOI18N
        jButton1.setText("REFRESCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jScrollPane1.setAutoscrolls(true);

        Productos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Productos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Productos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        Productos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Productos.getTableHeader().setReorderingAllowed(false);
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Productos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CONTROLSOFTWARE - COPYRIGHT 2023 - ING. JUNIOR MORALES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(se, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(se, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (!buscar.getText().isEmpty()) {

            if (activo.isSelected() && dni.isSelected()) {
                bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.estado=1 and C.identidad like '%" + buscar.getText() + "%' and C.cia=" + ControlSoftware.cia, Productos);
            }
            if (activo.isSelected() && rtn.isSelected()) {
                bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes  C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.estado=1 and C.rtn like '%" + buscar.getText() + "%' and C.cia=" + ControlSoftware.cia, Productos);
            }
            if (activo.isSelected() && nombre.isSelected()) {
                bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.estado=1 and C.nombre like '%" + buscar.getText() + "%' and C.cia=" + ControlSoftware.cia, Productos);
            }
            if (!activo.isSelected() && dni.isSelected()) {
                bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.identidad like '%" + buscar.getText() + "%' and C.cia=" + ControlSoftware.cia, Productos);
            }
            if (!activo.isSelected() && rtn.isSelected()) {
                bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.rtn like '%" + buscar.getText() + "%' and C.cia=" + ControlSoftware.cia, Productos);
            }
            if (!activo.isSelected() && nombre.isSelected()) {
                bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.nombre like '%" + buscar.getText() + "%' and C.cia=" + ControlSoftware.cia, Productos);
            }
        } else {
            bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.cia=" + ControlSoftware.cia, Productos);
        }
        if (activo.isSelected() && buscar.getText().isEmpty()) {
            bd.LlenarTabla("select C.idcliente as COD, C.nombre as NOMBRE, C.RTN AS RTN, C.IDENTIDAD AS ID, C.DIRECCION AS DIRECCION, D.DEPARTAMENTO AS DEPARTAMENTO, CI.CIUDAD AS CIUDAD, C.SALDO AS SALDO from clientes C INNER JOIN CIUDAD CI ON CI.ID_CIUDAD=C.CIUDAD INNER JOIN DEPARTAMENTO D ON D.ID_DEPARTAMENTO=C.DEPARTAMENTO where C.estado=1 and C.cia=" + ControlSoftware.cia, Productos);
        }
        autoajustar();

    }//GEN-LAST:event_jButton1ActionPerformed
    void autoajustar() {
        // Obtén el TableColumnModel de tu JTable
        TableColumnModel columnModel = Productos.getColumnModel();

// Itera sobre las columnas y ajusta su tamaño al contenido
        for (int columnIndex = 0; columnIndex < columnModel.getColumnCount(); columnIndex++) {
            TableColumn column = columnModel.getColumn(columnIndex);
            int width = 0;

            // Ajusta el ancho de la columna según el contenido de las celdas
            TableCellRenderer renderer = column.getHeaderRenderer();
            if (renderer == null) {
                renderer = Productos.getTableHeader().getDefaultRenderer();
            }
            Component headerComponent = renderer.getTableCellRendererComponent(Productos, column.getHeaderValue(), false, false, 0, columnIndex);
            width = headerComponent.getPreferredSize().width;

            for (int row = 0; row < Productos.getRowCount(); row++) {
                renderer = Productos.getCellRenderer(row, columnIndex);
                Component component = renderer.getTableCellRendererComponent(Productos, Productos.getValueAt(row, columnIndex), false, false, row, columnIndex);
                width = Math.max(width, component.getPreferredSize().width);
            }

            // Establece el ancho ajustado para la columna
            column.setPreferredWidth(width);
        }

// Ajusta el tamaño de las columnas al contenido
        Productos.getTableHeader().resizeAndRepaint();
    }
    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        // TODO add your handling code here:
        int pick = Productos.getSelectedRow();
        String u = "" + Productos.getValueAt(pick, 0);
        String v = "" + Productos.getValueAt(pick, 1);
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();

            estado_de_cuenta.codcliente.setText(u);
            estado_de_cuenta.descliente.setText(v);
            estado_de_cuenta.jButton1.doClick();
            dispose();

        }
    }//GEN-LAST:event_ProductosMouseClicked

    private void ProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMousePressed
        // TODO add your handling code here:
        int pick = Productos.getSelectedRow();
        se.setText("" + Productos.getSelectedRow());
        selected = Integer.parseInt(Productos.getValueAt(Integer.parseInt(se.getText().toString()), 0).toString());
    }//GEN-LAST:event_ProductosMousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_buscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionarcliente_estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionarcliente_estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionarcliente_estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionarcliente_estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionarcliente_estado_cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Productos;
    private javax.swing.JCheckBox activo;
    private javax.swing.JTextField buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dni;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton nombre;
    private javax.swing.JRadioButton rtn;
    private javax.swing.JTextField se;
    // End of variables declaration//GEN-END:variables
}
